export const Location = {
  US: "United States",
  UK: "United Kingdom",
  CANADA: "Canada",
  AUSTRALIA: "Australia",
  INDIA: "India",
  JAPAN: "Japan",
  CHINA: "China",
  RUSSIA: "Russia",
  FRANCE: "France",
  GERMANY: "Germany",
  SWITZERLAND: "Switzerland",
  SPAIN: "Spain",
  ITALY: "Italy",
  PORTUGAL: "Portugal",
  MEXICO: "Mexico",
  EGYPT: "Egypt",
  SOUTH_AFRICA: "South Africa",
  AFRICA: "Africa",
  NIGERIA: "Nigeria",
  KENYA: "Kenya",
};
