export const Skills = {
  DOCKER: "Docker",
  JAVASCRIPT: "JavaScript",
  NODE_JS: "Node.js",
  REACT: "React",
  REACT_NATIVE: "React Native",
  AWS: "AWS",
  GCP: "GCP",
  MICROSOFT_AZURE: "Microsoft Azure",
  PYTHON: "Python",
  SQL: "SQL",
  CI_CD: "CI/CD",
  TESTING: "Testing",
  DATA_SCIENCE: "Data Science",
  FRONT_END_DEVELOPMENT: "Front-End Development",
  BACK_END_DEVELOPMENT: "Back-End Development",
  UI_UX_DESIGN: "UI/UX Design",
  LEADERSHIP: "Leadership",
  TECHNICAL_WRITING: "Technical Writing",
  PROJECT_MANAGEMENT: "Project Management",
  LEADERSHIP_SKILLS: "Leadership Skills",
  ENGLISH: "English",
  SPANISH: "Spanish",
  FRENCH: "French",
  ITALIAN: "Italian",
  PORTUGUESE: "Portuguese",
  GERMAN: "German",
};
